### ISSUE TITLE
$nextTick vs x-transition

### ISSUE THREAD

**Issue by carlmjohnson** [alpinejs/alpine#438]
I have a modal that I'm fading in with an x-transition. I also want to focus it, so I tried writing `this.$nextTick(()=> { this.$refs.content.focus(); });`, but that doesn't work because the transition hasn't finished yet when $nextTick fires. Is there a way for $nextTick to deal with this, or do I just have to use window.setTimeout and keep it in sync with the length of the transition manually?

**Comment by HugoDF** [comment]
This is an interesting one.

The question boils down to whether `$nextTick` should trigger the callback after the transition finished right?

The issue here is that for something to transition, technically you have to run multiple renders & `$nextTick` is supposed to run after the next render.

By that logic, `$nextTick` can't run after the transition ie. the _last_ render of the transition, since it runs after the _first_ render.

Maybe we should have a different hook for this use case, but good catch.

**Comment by muzafferdede** [comment]
There are few alternative ways could be done by adjusting few core code, like hooking a callback in the end of the transition, or if it's possible to ask $nextTick to wait transition end. But i guess these kind of things should be expected with V3. So, setTimeout is your best friend for now.

**Comment by HugoDF** [comment]
> There are few alternative ways could be done by adjusting few core code, like hooking a callback in the end of the transition, or if it's possible to ask $nextTick to wait transition end. But i guess these kind of things should be expected with V3. So, setTimeout is your best friend for now. 

Yes the crux of it is also "should nextTick wait until the end of the transition"

**Comment by ahmedkandel** [comment]
This has been discussed in #491 , @carlmjohnson if I got you right you don't need to wait until the transition finish. This PR may fix your problem #502 

Maybe having a different hook after the transition finish is useful for other use cases

**Comment by carlmjohnson** [comment]
Neat. I think #502 would fix this, at least for my fading modal.

**Comment by HugoDF** [comment]
Does this PR that has gone in fix this issue? https://github.com/alpinejs/alpine/pull/555

**Comment by carlmjohnson** [comment]
As of right now, there hasn't been a release yet. I'll try to check after there has been.

**Comment by HugoDF** [comment]
@carlmjohnson you can try it out using https://cdn.jsdelivr.net/gh/alpinejs/alpine@master/dist/alpine.min.js as the CDN URL

**Comment by muzafferdede** [comment]
This should be fixed since #536 is merged as well and it solves most of the transitions bugs. With #555 all should be good.

**Comment by HugoDF** [comment]
This has been released in 2.4.0 I believe, feel free to re-open if we somehow regress (or it didn't quite solve the issue)

**Comment by SimoTod** [comment]
Here you can find a couple of examples using nextTick with transitions: a standard transition and a slow and nested one. 
Both should work as expected now.

**Comment by itsfaqih** [comment]
I think this issue need to be re-open since the issue is still exists #2284
